- name: configuring cart server
  hosts: cart
  become: yes
  tasks:
  - name: disabling nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabling nodesjs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.dnf:
      name: npm
      state: present


  -  name: configuring system user
     ansible.builtin.user:
      name: roboshop
      system: true
      home: /app/
      shell: /sbin/nologin/

  - name: make app directory
    ansible.builtin.file:
      state: directory
      path: /app/


  - name: download cart code 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip

  # - name: download cart code and unzip
  #   ansible.builtin.unarchive:
  #     src: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
  #     dest: /tmp/cart.zip
  #     remote_src: yes


  - name: unzipping
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app/
      remote_src: yes


  - name: dependencies installation
    community.general.npm:
      path: /app/


  - name: copying service file
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemon_reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: start cart service
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes

      
