- name: configuring catalogue server
  hosts: catalogue
  become: yes
  tasks: 

  - name: disable nodejs module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: creating system user
    ansible.builtin.user:
      name: Roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading catalogue code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

 
 #zthis module thinks file exists on ansible control server ,needs to extract on to remote machine
  - name: extracting 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes #file already exists in catalogue server


  - name: dependencies
    community.general.npm:
      path: /app/


  - name: copying systemctl service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service


  - name: daemond reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: starting the service
    ansible.builtin.service:
      name: catalogue
      enabled: yes
      state: started

  - name: copying mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present    
  
    # community.mongodb.mongodb_shell:
    #   file: /app/db/master-data.js
    #   idempotent: yes
    #   login_host: mongodb.raheemweb.fun

  - name: check products loaded or not
    ansible.builtin.command:  mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output


  - name: printing the data
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0


